### ISSUE TITLE
Korebuild 2.0 should launch the appropriate powershell exe

### ISSUE THREAD

**Issue by javiercn** [aspnet/KoreBuild#102]
build.cmd should launch the powershell executable with the right bitness (x86 or x64) depending on the architecture of the machine it is running

**Comment by analogrelay** [comment]
This is out of date

**Comment by analogrelay** [comment]
Actually, this wasn't specific to the existing aspnet-build, so never mind :)

**Comment by natemcmaster** [comment]
We're removing KoreBuild 2.0 #197. Closing as wont-fix
