### ISSUE TITLE
Custom Temp Folder

### ISSUE THREAD

**Issue by wangkanai** [aspnet/KoreBuild#111]
I see that KoreBuild generate output to with guid added to the folder and package version.

```
tempFolder="/tmp/KoreBuild-$(uuidgen)"  
```

Is there a way to make `tempFolder` be like `KoreBuild-$(build-version)`
Thank you

**Comment by muratg** [comment]
KoreBuild is an internal tool for building ASP.NET and not recommended for any other use.
