### ISSUE TITLE
Find a way to embed the git sha in the assembly info

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KoreBuild#14]
We can use the AssemblyMetadataAttribute but we need a way to integrate it. Maybe we can set and environment variable that the runtime can use to populate assembly info on the fly instead of editing files.

https://github.com/aspnet/Universe/issues/64

**Comment by muratg** [comment]
@victorhurdugaci may have some thoughts on this too

**Comment by victorhurdugaci** [comment]
It wouldn't be too hard to set an environment variable on the CI with the commit id but does the CLI support `AssemblyMetadataAttribute` from an environment variable?

**Comment by davidfowl** [comment]
Nope I think we need to generate files on build

**Comment by victorhurdugaci** [comment]
That might be possible too. I'm working now on storing the commit hashes from the universe build so we can sync the tests to the same version during the test pass. I think I can piggy back on it to generate the files

**Comment by victorhurdugaci** [comment]
Fixed by https://github.com/aspnet/KoreBuild/pull/18
