### ISSUE TITLE
Update travis.yml files with new osx_image

### ISSUE THREAD

**Issue by cesarblum** [aspnet/KoreBuild#140]
Not sure this is the right repo but seemed the most appropriate.

![image](https://cloud.githubusercontent.com/assets/924164/20992680/8c333d8c-bc9a-11e6-831f-adc35b0f257e.png)

https://travis-ci.org/aspnet/KestrelHttpServer/jobs/181767609

Need to update

```
osx_image: xcode7.1
```

to

```
osx_image: xcode7.3
```

in our `.travis.yml` files.

cc @muratg @pranavkm

**Comment by pranavkm** [comment]
@NTaylorMullen could you take this one?

**Comment by NTaylorMullen** [comment]
Sure

**Comment by NTaylorMullen** [comment]
Done.
