### ISSUE TITLE
`build install` doesn't work

### ISSUE THREAD

**Issue by pranavkm** [aspnet/KoreBuild#17]
In DNX, `build install` would install to the %UserProfile%.dnx\packages directory in the event the publish directory isn't specified. This worked nicely since DNX would look for packages installed in this directory and would use them during restore. However this doesn't work now since `dotnet restore` doesn't use this directory as a source (unless it's manually listed). 

What should be the behavior for `build install` if the `PACKAGES_PUBLISH_DIR` env variable we use as target is not specifed? Would the user have to edit the nuget.config to make `build install` work now?

**Comment by pranavkm** [comment]
cc @moozzyk

**Comment by moozzyk** [comment]
`%UserProfile%.nuget\packages` ?

**Comment by pranavkm** [comment]
We could add it there but the user would've to add that directory as a source for it to work in restores.

**Comment by javiercn** [comment]
Can we make this default to %UserProfile%.nuget\packages?

**Comment by pranavkm** [comment]
> We could add it there but the user would've to add that directory as a source for it to work in restores.

**Comment by javiercn** [comment]
@pranavkm I thought the %userprofile%.nuget\packages was something standard, if it is not, can we pass --source and include it when we call dotnet restore? I believe that will work (it will add it as an extra source)

**Comment by pranavkm** [comment]
Great. We can default it to `$env:NUGET_PACKAGES ?? $env:USERPROFILE\.nuget\packages`. Sound good? The workflow would be

repo1> `.\build install`
repo2> `dotnet restore -s $env:USERPROFILE\.nuget\packages`

**Comment by javiercn** [comment]
And doing .\build.cmd would run dotnet restore -s $env:USERPROFILE.nuget\packages as part of the build?

**Comment by pranavkm** [comment]
Nope. You'd have to explicitly opt into that behavior. Hence the explicit `dotnet restore -s $env:USERPROFILE\.nuget\packages`

**Comment by moozzyk** [comment]
:+1:

**Comment by javiercn** [comment]
Why would you have to opt-in into it? build install is our own creation, so we should make it easy to work with. Having to run dotnet restore manually on each project is not good (it hasn't worked for me running it at the top folder, probably because we have a global.json)

**Comment by pranavkm** [comment]
One of the reasons dotnet restore does not use the .nuget\packages dir as a source is so that you do not have to delete the directory when switching between incompatible feeds. This is a nice feature that we do not want to regress in the default case.

**Comment by javiercn** [comment]
What about doing it under a flag? --use-installed

**Comment by pranavkm** [comment]
:+1: we can pass the `.nuget` directory as a `fallbacksource` (?) in that case.

**Comment by balneaves** [comment]
Is it possible to do a nuget publish without nuget add?  I can't see a way to skip the `nuget-packages-add` step, which I don't need on our build server... I just want the `nuget-resilient-publish` to push to our local nuget server running under Nexus.

Bit of a hack, but I only really care because I cant get `nuget add` to work on CentOS... it just hangs after `Installing...` without any error, and can't even Ctrl-C out of it.

**Comment by Eilon** [comment]
@pranavkm @javiercn @moozzyk , is this still needed?

**Comment by pranavkm** [comment]
It'll be nice to have

**Comment by javiercn** [comment]
I basically set the packages publish dir on my powershell profile, but it would definitely be nice for the build script to do it automagically

**Comment by Eilon** [comment]
I don't think the build would ever do this automatically. When I just run `build` on a machine I don't want it installing the packages in some place that affects other projects on my machine.

**Comment by smitpatel** [comment]
presently installed packages are in the folder named `-expand` in repo root due to empty argument for installation directory and using the next argument as the name

```
info:   program: .build/nuget.exe
info:   commandline: add D:\ef101\EntityFramework\artifacts\build\Microsoft.EntityFrameworkCore.Relational.Design.1.0.1.nupkg -source  -expand
info:   workingdir: D:\ef101\EntityFramework
infoSuccessfully added package 'D:\ef101\EntityFramework\artifacts\build\Microsoft.EntityFrameworkCore.Relational.Design.1.0.1.nupkg' to feed '-expand'.
```

Ref: https://github.com/aspnet/KoreBuild/blob/dev/build/shade/_nuget-packages-add.shade#L27

**Comment by pranavkm** [comment]
I don't think there's a lot of value in doing this work item. I'd rather not have the build script edit NuGet.configs in the repo (or the global one) which is the only way to make this work. If somebody else feels strongly about this work item, feel free to send a PR 😃
