### ISSUE TITLE
Remove dependency on Sake

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/KoreBuild#174]
This is a non-trivial change. Lots of our build scripts are written in Sake. This code has to be ported to MSBuild or powershell before we can remove Sake completely.

**Comment by davidfowl** [comment]
RIP sake

**Comment by natemcmaster** [comment]
As a part of this @pranavkm and I want to change out our build scripts handle trailing arguments (`$@`). New syntax would add trailing args to the main MSBuild invocation. e.g. `build.cmd /t:TargetName`. Would let us to things like `build.cmd /p:CoreFxVersion=4.4.0-nightly /v:normal /logger:CustomLogger` etc.
