### ISSUE TITLE
"Restore" target in standard-lifecycle overrides the Restore target from Microsoft.Common.targets

### ISSUE THREAD

**Issue by pranavkm** [aspnet/KoreBuild#177]
Run `dotnet restore makefile.proj /p:LifecycleType=Standard`.

Expected:
We restore the packages listed in makefile.proj.

Actual:
The `Restore` target is invoked which does not include the makefile.proj. Consequently build tools like `NuGetPackageVerifier` aren't part of restore output.

**Comment by natemcmaster** [comment]
Rename our standard target to "Initialize"?

**Comment by pranavkm** [comment]
Yup, that's what I did. Alternatively we could prefix our targets so it's less ambiguous (although I suspect this isn't a common MSBuildism).
