### ISSUE TITLE
Build.cmd truncates double-quoted arguments containing a semicolon

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/KoreBuild#179]
**Repro:**
`build.cmd /t:"Compile;Package" /v:d`
or `build.cmd "/t:Compile;Package" /v:d`

build.ps1 receives:
```ps1
$args = ('/t:Compile')
```

Should receive
```ps1
$args = ('/t:Compile;Package', '/v:d')
```

**Workaround:**
Use single quotes
`build.cmd '/t:Compile;Package' /v:d`

**Comment by natemcmaster** [comment]
~~Even worse....it will combine multiple, single quoted args:
`build.cmd '/t:Compile;Package' '/p:Prop=A b'` => `$args = ('/t:Compile;Package /p:Prop=A b')`~~

**Comment by natemcmaster** [comment]
FYI the double-quoted issue remains, but the issue mentioned in my previous argument was resolved by updating the build.ps1 script to use splatting correctly.

**Comment by dougbu** [comment]
@natemcmaster coming back to this issue, I'm wondering if it really matters. Thoughts?

Those concerned about careful quoting can drop into PowerShell and invoke `build.ps1` directly. Or they can double-up their escape characters when using `build.cmd` e.g. using single quotes (as you demonstrated) or `^`. All sound better than complicating `build.cmd`.

FYI, though I've written some ugly re-escaping code in the past, I found nothing more complicated than `%*` in my current `%Path%`.

**Comment by natemcmaster** [comment]
Yeah, we fixed most of this by changing `build.ps1 $args` to `build.ps1 @args`. I'm going to close because more work on this is likely not worth the effort. Re-open if you still think it's a high enough priority.
