### ISSUE TITLE
DefaultItems.targets should calculate `@(Solutions)` consistently with other `$(RepositoryRoot)` uses

### ISSUE THREAD

**Issue by dougbu** [aspnet/KoreBuild#182]
`$(RepositoryRoot)` always ends with a slash and code removing members of item groups must match existing members' text. .props and .targets files in this repo should therefore use properties consistently when creating item groups. Unfortunately [line 8 in DefaultItems.targets](https://github.com/aspnet/KoreBuild/blob/feature/msbuild/build/targets/DefaultItems.targets#L8) does not follow this recommendation.

Remove the slash after `$(Repository)` root, allowing `@(ExcludeSolutions)` to work as expected.

**Comment by natemcmaster** [comment]
https://github.com/aspnet/KoreBuild/commit/5010eac5e70ef8b5a09aac786601c721d5443912
