### ISSUE TITLE
Install 2.0.0-beta-* runtime

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KoreBuild#190]
KoreBuild should start installing the 2.0.0-beta-* runtime (which matches the current version on the MyGet feed).  This should be sufficient to start moving repos to 2.0.  We want to move Benchmarks to 2.0 ASAP.

CC: @davidfowl

**Comment by natemcmaster** [comment]
Duplicate of https://github.com/aspnet/Coherence/issues/166. We're working on it.
