### ISSUE TITLE
Use NuGet-based .NET Framework ref assemblies instead of using .NET targeting packs

### ISSUE THREAD

**Issue by Eilon** [aspnet/KoreBuild#211]
Currently on Windows the builds require the .NET Framework Targeting Pack to be installed on the machine.

We should use the NuGet-based packages instead because they should work on all platforms.

**Comment by kevinchalet** [comment]
@Eilon on a related note, do you plan to add the 4.7 reference assemblies in the NETFrameworkReferenceAssemblies package in the near future?

**Comment by Eilon** [comment]
@PinpointTownes hmm if we need them there we would of course add them 😄 But I don't think we need them at this time. I don't think there's much new API in .NET 4.7 that applies to web stuff, though, is there?

**Comment by kevinchalet** [comment]
> I don't think there's much new API in .NET 4.7 that applies to web stuff, though, is there?

.NET 4.7 brings the great ECDSA methods that were added as part of .NET Standard 1.6 last year (I use them in my OIDC server project). Without a 4.7 reference assemblies package, this means all my Travis build will fail with a `MSB3644` error if I add a net47 TFM: https://travis-ci.org/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/jobs/220646814#L626

**Comment by Eilon** [comment]
Closing because this doesn't seem very important anymore.
