### ISSUE TITLE
Add retries when downloading nuget.exe

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KoreBuild#214]
KoreBuild should add retries when downloading nuget.exe to prevent build breaks.

https://github.com/aspnet/KoreBuild/blob/dev/build/KoreBuild.ps1#L94-L99
https://github.com/aspnet/KoreBuild/blob/dev/build/KoreBuild.sh#L147-L151

**Comment by pranavkm** [comment]
We can probably remove the one from KoreBuild.sh.

**Comment by mikeharder** [comment]
Another failure: http://aspnetci/viewLog.html?buildId=206695&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win10Universe

```
  Invoke-WebRequest : Unable to connect to the remote server
  At C:\BuildAgent\work\2b0c8ce712895332\.r\KestrelHttpServer\.build\KoreBuild.ps1:101 char:5
  +     Invoke-WebRequest "https://dist.nuget.org/win-x86-commandline/v4. ...
  +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
     eption
      + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
   
C:\BuildAgent\work\2b0c8ce712895332\build\RepositoryBuild.targets(60,5): error MSB3073: The command "./build.cmd /t:Verify /p:BuildNumber=24579 /p:Configuration=Release" exited with code 1.
```

**Comment by natemcmaster** [comment]
Closed by removing the NuGet.exe download. As far as we could tell, none of our build scripts actually use this anymore now that we have `dotnet nuget`.
