### ISSUE TITLE
Build Scripts: Fail fast on missing dependencies

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KoreBuild#218]
Our build scripts (e.g. build.cmd, build.sh) should fail fast if required dependencies are not present, and provide instructions for how to install them.  A good test is to clone and build on a clean VM with only the OS installed.

## build.sh
* [ ] `unzip` required to decompress KoreBuild.zip
  * Alternatively, we could generate KoreBuild.tar.gz for Linux and remove the dependency on `unzip`
* [ ] All dependencies required by .NET Core SDK and Runtime (e.g. `libunwind`)

## build.cmd
* [ ] .NET Framework Developer Packs

**Comment by Eilon** [comment]
Closing because it seems it would be very difficult to keep this up-to-date. As we add new dependencies, we'd need to remember to add checks. But even worse, as we remove dependencies, we'd need to remember to remove the checks, or else we'd fail for no good reason.
