### ISSUE TITLE
Old 1.2.0 version still appearing in some props files

### ISSUE THREAD

**Issue by Eilon** [aspnet/KoreBuild#222]
The old 1.2.0 version appears in some props files:
* https://github.com/aspnet/KoreBuild/blob/dev/template/build/dependencies.props#L11
* https://github.com/aspnet/KoreBuild/blob/dev/template/version.props#L4

@natemcmaster - are these not used? Or are they some global default that's always overridden?

**Comment by natemcmaster** [comment]
They're just templates for new projects. Not actually used.

**Comment by Eilon** [comment]
So... delete them? Or update them?

**Comment by Eilon** [comment]
Or add a comment to those lines so that whoever creates a new project knows to update them to whatever is appropriate for their project maybe?

**Comment by natemcmaster** [comment]
> add a comment to those lines 

:+1:

**Comment by Eilon** [comment]
Got it, thanks!
