### ISSUE TITLE
Add a way to disable package restore when building repos

### ISSUE THREAD

**Issue by kichalla** [aspnet/KoreBuild#224]
Sometimes I want to just work with the packages which are already present on my machine. Without this frequent coherence builds cause package restore failures when building a repo.

cc @dougbu

**Comment by Eilon** [comment]
Is the issue more about packages not being coherent, or about not wanting to get any new packages at all?

**Comment by dougbu** [comment]
For me, the issue is about not wanting any new packages. I want to be able to _choose_ when it's time to `git pull` and, even more often, want to build from root when disconnected.

**Comment by kichalla** [comment]
> Is the issue more about packages not being coherent, or about not wanting to get any new packages at all?

yeah the first case because at the time filing of this bug there were frequent successful coherence builds and doing a build locally would fail due to coherent set not available. Earlier there used to be a switch to disable restore if it was already done. We need something like that again.
