### ISSUE TITLE
Use binary logger

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/KoreBuild#225]
https://github.com/Microsoft/MSBuild/wiki/Binary-Log

**Comment by davidfowl** [comment]
Because it's structured and there's a tool to make the output readable?

**Comment by natemcmaster** [comment]
Has lot of benefits. Smaller file, faster output, and contains more detail. And yes there is a a viewer already. https://github.com/KirillOsenkov/MSBuildStructuredLog

**Comment by davidfowl** [comment]
So when we use the binary log and something fails on the CI what does it look like? Or would we still be logging on team city?

**Comment by natemcmaster** [comment]
it would produce a file in artifacts/. We already produce a plaintext file log, and I'm thinking this would replace that. We would leave console logging as is.

**Comment by Eilon** [comment]
An interesting new feature, but the value doesn't seem to be there. We would still keep the console logger (for humans) and the text log (for easy searchability with <kbd>Ctrl</kbd>+<kbd>F</kbd> in any tool.

**Comment by analogrelay** [comment]
I think this has value. I've been doing some MSBuild spelunking and the structured log is over 9000 times more efficient. It doesn't really harm us to generate the log, we can continue to generate the text log as well. Even if we did want to remove the text log to save space, it is easy to regenerate the text log from the binary log using the replay feature.

I will say that for something like Universe, the log is large (smaller than the text log though) and loading a whole Universe log up in the viewer is problematic (right now, though the tool probably needs optimization). Still, it should have little-to-no-impact on the build time to generate it (we can measure to be sure).

**Comment by natemcmaster** [comment]
Some data: run `build.cmd /bl` on aspnet/Common:

Output:

**artifacts/msbuild/msbuild.log** (file logger)
132.4 MB

**msbuild.binlog** (binary logger)
5.7 MB
