### ISSUE TITLE
Determine a way to update the version files on dev machines when a new version of Microsoft.NETCore.App is added to the feed

### ISSUE THREAD

**Issue by pranavkm** [aspnet/KoreBuild#226]
This is a more general purpose problem, but might be made worse when we decide to do this https://github.com/aspnet/CoreCLR/issues/185. When a new version of Microsoft.NETCore.App is added to the feed the shared-runtime.version in KoreBuild also needs to be updated. Failure to do so would cause samples \ tests to start failing. The current way to resolve this today is by deleting the .build directory and calling build locally. We should determine if there's a way to smoothen this experience.

**Comment by natemcmaster** [comment]
Was this resolved by using bundled versions?

**Comment by pranavkm** [comment]
Yup.
