### ISSUE TITLE
Ensure that Mirror Publish cannot break builds in-progress

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KoreBuild#228]
Looks like it's still possible for builds to fail during mirror publish.  If newer packages are pushed to our feed, the packages may be newer than the shared runtime.

```
[11:40:02] :	 [Step 3/3]   Starting test execution, please wait...
[11:41:02] :	 [Step 3/3]   Testhost process exited with error: It was not possible to find any compatible framework versionThe specified framework 'Microsoft.NETCore.App', version '2.0.0-preview1-002059-00' was not found.  - Check application dependencies and target a framework version installed at:      /  - Alternatively, install the framework version '2.0.0-preview1-002059-00'.
```

http://aspnetci/viewLog.html?buildTypeId=XPlat_Mac_MacUniverseCoreCLR&buildId=206322

We improved this scenario in https://github.com/aspnet/KoreBuild/issues/209, but it wasn't the complete fix.

**Comment by kichalla** [comment]
One way of fixing this would be to pass in the 'shared-runtime-version' as a property to each repository that we build. So we lock all the repos which are being built in a universe build to the version which was started to start the build.
https://github.com/aspnet/Universe/blob/dev/build/RepositoryBuild.targets#L51

As discussed earlier, this does not solve the issue where other packages with wildcard are present.

One more options which @pranavkm suggests is to use the PinVersionUtitlity to pin the version when building

**Comment by natemcmaster** [comment]
Another thing to consider: some tests run dotnet-restore to test end-to-end scenarios. e.g. dotnet-watch and possible MvcPrecomplication tests

**Comment by mikeharder** [comment]
This issue was moved to aspnet/Coherence-Signed#458
