### ISSUE TITLE
Why does korebuild download dotnet 1.0.4?

### ISSUE THREAD

**Issue by davidfowl** [aspnet/KoreBuild#242]
Why does korebuild download dotnet 1.0.4?

![image](https://cloud.githubusercontent.com/assets/95136/26021405/0783cb70-3741-11e7-897e-2d4a76887836.png)

/cc @pakrym @kichalla @natemcmaster

**Comment by natemcmaster** [comment]
Because our build tools still need it. This is probably a dup of https://github.com/aspnet/BuildTools/issues/200, which is about moving our build tools to run on .NET Core 2

**Comment by davidfowl** [comment]
Okies. We need to make it more reliable

**Comment by mikeharder** [comment]
I created an issue to add retries when calling dotnet-install: https://github.com/aspnet/KoreBuild/issues/245

**Comment by natemcmaster** [comment]
Tracking remaining work here: https://github.com/aspnet/BuildTools/issues/200
