### ISSUE TITLE
Merge private copy of dotnet-install scripts into CLI

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KoreBuild#247]
The dotnet-install scripts in the KoreBuild repo started as a copy of the scripts in the CLI repo (https://github.com/dotnet/cli/tree/master/scripts/obtain), but have since diverged.  We should merge any improvements in the KoreBuild scripts back into the CLI scripts, then either:

* Remove the scripts from the KoreBuild repo, then have KoreBuild download the scripts from the CLI repo at runtime.
* Keep a copy of the scripts in the KoreBuild repo, but only update them when the copy in the CLI repo changes.

I would lean towards downloading the scripts from the CLI repo by default, with the option to use a private copy if and when needed (e.g. to workaround a bug or breaking change).

**Comment by mikeharder** [comment]
It would be good if we can complete this in the next few days.  The CLI is planning some renames and updates to their install scripts, and we will need to merge those changes to ingest new CLI builds.

**Comment by mikeharder** [comment]
We decided to keep our own copy of the scripts in the KoreBuild repo, but only update them when the copy in the CLI repo changes.

**Comment by kichalla** [comment]
e35d65aca7b22985ac3f38f0db3ba0be23b199e7
