### ISSUE TITLE
RESX target should depend on restore

### ISSUE THREAD

**Issue by rynowak** [aspnet/KoreBuild#248]
If you run `.\build.cmd /t:resx` you will get a bunch of errors like:
```
D:\k\Routing\.build\targets\Project.CSharp.Resx.targets(17,5): warning : Could not generate resx files. This project doe
s not reference Internal.AspNetCore.Sdk. [D:\k\Routing\src\Microsoft.AspNetCore.Routing\Microsoft.AspNetCore.Routing.csp
roj]
```

do a restore, and they go away.

**Comment by natemcmaster** [comment]
How about improving the error to say "run restore first" if it detects that step hasn't been done yet? restore is slow and I avoid doing it as much as possible...esp when I'm making frequent minor tweaks to resx

**Comment by Eilon** [comment]
Closing because this seems like a fairly minor problem. If more people feel pain around this we will revisit.
