### ISSUE TITLE
Add pre-build step for compiling MSBuild tasks 

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/KoreBuild#254]
Several of our repos need custom tasks as a part of build. Because these must be compiled before the main build process is started, we'd need to add a new step to korebuild.ps1/sh

1. preflight restore (no changes)
2. compile tasks projects (the new step)
    1. Restore projects in build/tasks/**/*.csproj
    2. Build projects in build/tasks/**/*.csproj
3. default lifecycle build (no changes)

This should reduce the need for console tools as much of our build work can be done as MSBuild tasks

cc @pranavkm @ryanbrandenburg

**Comment by pranavkm** [comment]
Could we limit it to one project (`build/tasks/RepoTasks.csproj`)? I can't think of a useful reason to have more than one task binary per repo.

**Comment by natemcmaster** [comment]
Good point. Yeah, one should be fine.

Second follow up idea, we could even put most of the RepoTasks.csproj definition in korebuild itself. This would include the packagereference to msbuild and any other common properties required by task projects. This would mean RepoTasks.csproj would be as simple as

```xml
<Project Sdk="Microsoft.NET.Sdk">
   <Import Project="$(KoreBuildTasks)" Condition="Exists('$(KoreBuildTasks)')" />
   <PropertyGroup>
       <TargetFramework>netstandard1.6</TargetFramework>
   </PropertyGroup>
</Project>
```
