### ISSUE TITLE
Handle environment variables consistently

### ISSUE THREAD

**Issue by dougbu** [aspnet/KoreBuild#259]
Scripts in this repo are not consistent between PowerShell and `bash` in how they handle environment variables. `KOREBUILD_SKIP_RUNTIME_INSTALL` and now `KOREBUILD_ENABLE_BINARY_LOG` must have the value `1` to change anything in `build/KoreBuild.ps1`. But, they only need to be non-empty to have the same affect in `build/KoreBuild.sh`.

All other environment variables are value overrides, not Boolean switches.  They're handled consistently and must be defined with a non-empty value to change anything.

Should handle the Boolean switches the same way in the PowerShell and `bash` scripts. Confirming they have the value `1` is probably the way to go. But, could also treat any non-empty value as `true`, matching the "override" environment variables and the current `bash` behaviour.

----

W.r.t. the empty / non-empty checks,`build/dotnet/dotnet-install.sh` is extra-careful when expanding `$DOTNET_INSTALL_DIR`, using `"${DOTNET_INSTALL_DIR:-}"`. This seems like overkill to me. But, I'd appreciate more opinions.

**Comment by Eilon** [comment]
Not planning to change this.
