### ISSUE TITLE
Why does KoreBuild install the .NET CLI to ~/.dotnet on Windows?

### ISSUE THREAD

**Issue by analogrelay** [aspnet/KoreBuild#272]
The default location `dotnet-install` uses is `%LocalAppData%\Microsoft\dotnet`, why are we installing to a different directory?

**Comment by analogrelay** [comment]
(I'd have just asked, but if there's a reason for it, I'd rather it be documented somewhere, and a GitHub issue seemed appropriate)

**Comment by natemcmaster** [comment]
https://github.com/aspnet/Announcements/issues/234

**Comment by natemcmaster** [comment]
The multi-hive feature ended up being cut, but since we'd made the breaking change already, it didn't seem worth the effort to revert.

**Comment by analogrelay** [comment]
Ok, sounds somewhat reasonable. I guess `dotnet-install` should be updated theoretically, but I assume that would be part of multi-hive/other acquisition improvements.
