### ISSUE TITLE
Dnxtools feed is not picked up from NuGet.config

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/KoreBuild#29]
Followup to https://github.com/aspnet/KoreBuild/pull/28

@victorhurdugaci @pranavkm @ryanbrandenburg

**Comment by pranavkm** [comment]
I think it's a CLI bug. We can revisit this once we upgrade the CLI again

**Comment by muratg** [comment]
Still an issue with the current CLI?

**Comment by Eilon** [comment]
@ajaybhargavb is this still an issue?

**Comment by ajaybhargavb** [comment]
Looks like its not. Just sent a PR to remove the feed.

**Comment by ajaybhargavb** [comment]
261793ea95c1f7a3b1c927408f9f1a757b268dcc
