### ISSUE TITLE
Set min required PowerShell version to 4

### ISSUE THREAD

**Issue by Eilon** [aspnet/KoreBuild#30]
To avoid people with Windows 7 and PowerShell 3 trying to run the build scripts.

**Comment by mikes-gh** [comment]
I was the one with the above issue.  It was a proxy server issue in the end.  I upgraded to PS 5 by the time I realised the problem but I suspect PS 3 would still work fine.
I think dotnet restore could come back with a better error if nugget sources aren't available.
