### ISSUE TITLE
Remove ShouldVerifyNupkgs

### ISSUE THREAD

**Issue by bricelam** [aspnet/KoreBuild#32]
The `nuget-verify` target is blazing fast. :fire: We should consider just always running it.

cc @Eilon @ajaybhargavb

**Comment by Eilon** [comment]
I'm fine with that. Should help prevent some CI failures.

@bricelam I assume it's fast even on a larger repo such as EF?

**Comment by bricelam** [comment]
Yeah, I ran it on the output of UniverseCoherence (across a network share to Azure) and it felt like it took less than a second.

**Comment by bricelam** [comment]
Oh wait, my results may not be conclusive. I think I just ran my rule, not all of them...

**Comment by bricelam** [comment]
171 packages with the `AdxVerificationCompositeRule` rule took 0:03:11 across the share. About a second a package... Not too horrible.

**Comment by Eilon** [comment]
That's pretty blazingly fast.

**Comment by Eilon** [comment]
I guess actually the rules that we run _within_ each repo are the fast ones. The slow ones that we run on Coherence-Signed and CoreCLR are the ones that check file signatures, etc.

**Comment by natemcmaster** [comment]
This is done. I runs by default now on repo builds.

**Comment by Eilon** [comment]
Oh yay 😄
