### ISSUE TITLE
Determine a way to specify that a project should not execute tests in parallel

### ISSUE THREAD

**Issue by pranavkm** [aspnet/KoreBuild#42]
Porting from https://github.com/aspnet/Universe/issues/407

We currently have a mechanism where specifying an environment variable would cause KoreBuild to specify `-parallel none` flag to runner. The environment variable is defined in several different places - the CI build configuration, in .travis.yml and in build.cmd \ build.sh. 
1. Customizing build.cmd \ build.sh causes issues makes it harder to bulk update these files (and might go away entirely with @victorhurdugaci's work).
2. Specifying it in the CI \ config files is a bad idea since we run it into issues with parallelism in local builds.

It would be nice for the embed this information in a per project basis and have the runners somehow figure this out so that `dotnet run` would flow it through.

**Comment by pranavkm** [comment]
Similarly we also need a way to figure out if a project needs to be skipped for a specific platform. We have code in DataProtection to allow us to skip compiling a particular package and it replicates a bunch of code from KoreBuild.

**Comment by natemcmaster** [comment]
These was done as a part of the MSBuild conversion. Repos can opt-out test projects on specific platforms in `repo.props` and test parallelization can be disabled using xunit.runner.json or assembly attributes.
