### ISSUE TITLE
Downloading KoreBuild.zip might need retry logic

### ISSUE THREAD

**Issue by pranavkm** [aspnet/KoreBuild#5]
Saw this on the CI:

```
[Building Testing] Downloading KoreBuild from https://github.com/aspnet/KoreBuild/archive/dev.zip
[23:04:33][Building Testing] Invoke-WebRequest : Unable to connect to the remote server
[23:04:33][Building Testing] At C:\ba\80aa54301e43fe12\Testing\build.ps1:23 char:5
[23:04:33][Building Testing] +     Invoke-WebRequest $koreBuildZip -OutFile $localZipFile
```

which went on to fail.

**Comment by BrennanConroy** [comment]
Also, if this fails (and the retries fail) we should return the error from the build script, currently the build finishes and says "succeeded"

**Comment by victorhurdugaci** [comment]
I have the feeling that's a universe bug and not a build.cmd. build.cmd returns 1 if the download fails

**Comment by BrennanConroy** [comment]
You're right...

**Comment by victorhurdugaci** [comment]
I'm fixing the retry now. Want to take a look at universe and why it thinks the build succeeded?

**Comment by BrennanConroy** [comment]
Looks like we just need to check if the zip was downloaded before continuing
