### ISSUE TITLE
Don't log restore output on travis-ci unless there is an error

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/KoreBuild#57]
For example, restore on Entity Framework produces thousands of lines of "warning" that are neglible. Because travis-ci limits log file size to 4MB, we should dump restore output to /dev/null unless there is an error. Travis cancels jobs that produce too much log output.

```
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

The job has been terminated
```

See https://travis-ci.org/aspnet/EntityFramework/builds/121926544 
cref https://github.com/NuGet/Home/issues/910#issuecomment-208436805

**Comment by BrennanConroy** [comment]
If restore takes 10+ minutes and we don't output any thing it will also fail, so be careful.

**Comment by natemcmaster** [comment]
Good to know. Simple solution: we could log a ping every minute to keep travis-ci going.

**Comment by natemcmaster** [comment]
from @joelverhagen 

> another workaround would be to set --verbosity error on the restore

**Comment by Eilon** [comment]
If we do this and set the verbosity to `error`, do we have `restore` operations that are likely to take 10min+ and thus fail on Travis? That's my main concern here.

**Comment by natemcmaster** [comment]
@Eilon yes, that is possible, especially for big projects such as EF and Mvc

**Comment by Eilon** [comment]
Yeah those are the ones I'm worried about... Is there some "intermediate" level of verbosity for restore that would emit _something_ but not as much as what we have now?

**Comment by natemcmaster** [comment]
> Is there some "intermediate" level of verbosity for restore ...?

Not that I'm aware of. I'm not sure what the best solution is here given that https://github.com/dotnet/cli/issues/1623 hasn't gained traction yet

**Comment by natemcmaster** [comment]
Fixed by CLI.
