### ISSUE TITLE
Stop installing DNX

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/KoreBuild#7]
The bootstrapping still installs the latest dnx. We don't need dnx anymore (or won't soon) so we can skip this

**Comment by Eilon** [comment]
We still need it in a couple of repos where we use DNX to run tests in VS, but we are planning to make that be an opt-in in the few repos that need it.

**Comment by muratg** [comment]
We'll get there soon :)

**Comment by davidfowl** [comment]
/cc @victorhurdugaci 

![image](https://cloud.githubusercontent.com/assets/95136/13508685/e1dc0208-e13c-11e5-98c1-9263fe1c6514.png)

**Comment by victorhurdugaci** [comment]
The repo is still called "dnx-tools". @Eilon ?

Oh... for the `DNX_` variables. are those still supported by the CLI?

**Comment by Eilon** [comment]
We'll some day rename the DnxTools repo. Don't really have a good name for it.

**Comment by victorhurdugaci** [comment]
"Alexander" - that's a good name :trollface:

**Comment by Eilon** [comment]
Doesn't sound Great to me... :smile:

**Comment by victorhurdugaci** [comment]
This is done
