### ISSUE TITLE
_node.shade is looking for node.exe in the wrong place

### ISSUE THREAD

**Issue by Matty666** [aspnet/KoreBuild#76]
If _node-install.shade is used to install node because it's not globally installed, it downloads it to the ".\bin\nodejs" folder. However, _node.shade looks for the locally installed file in the ".\bin\node" folder.

**Comment by muratg** [comment]
@DJMatty Just curious -- why are you using KoreBuild?

**Comment by Matty666** [comment]
It's a nice single command build system, it fetches the dotnet sdk if its not there, fetches node/npm etc. if they aren't there and then builds the projects. We modified the makefile.shade to build our projects, and it builds our projects on a minimal build agent (currently it needs the vs2015 build tools and the vc redist, because of xunit relying on it), or on our dev machines.

**Comment by natemcmaster** [comment]
We are removing the Sake targets, including the target that installs node.
