### ISSUE TITLE
build.cmd should create a log file

### ISSUE THREAD

**Issue by mikeharder** [aspnet/KoreBuild#86]
I think build.cmd should create a log file, including things like detailed test results (including the time to execute each test).  Would be nice to keep the 10 most recent logs (`build.log`, `build.1.log` ...  `build.9.log`), but even a single log of the most recent build would be nice.

This came up when I ran `build.cmd`, and Kestrel unit tests took 120 seconds rather than the usual 6 seconds, but I cannot repro and I don't know what caused it (e.g. was it a single slow test or all tests).  A build log showing unit test timing would have been helpful.

**Comment by muratg** [comment]
cc @pranavkm @anurse

**Comment by muratg** [comment]
@anurse Were you planning to add something like this in korebuild2?

**Comment by natemcmaster** [comment]
https://github.com/aspnet/KoreBuild/pull/159 started producing a file log to artifacts/msbuild/msbuild.log. Good enough?

**Comment by mikeharder** [comment]
LGTM
